name: vruksh_guru
description: A new Flutter project.


publish_to: "none" 













version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"







dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.2.0
  google_api_headers: ^1.3.0
  google_maps_webservice: ^0.0.19
  google_maps_flutter: ^2.2.1
  rect_getter: ^0.1.0
  flutter_custom_clippers: ^1.1.1
  flutter_rating_bar: ^3.0.1+1
  line_awesome_icons: ^1.0.4+2
  animated_widgets: ^1.0.6
  page_transition: ^2.0.9
  flutter_map: ^0.14.0
  dio: ^5.0.3
  carousel_slider: ^4.2.1
  intl: ^0.17.0
  flutter_google_places_hoc081098: ^1.2.0
  google_maps_flutter_web: ^0.4.0+5
  geolocator: ^9.0.2
  booking_calendar: ^1.1.9
  flutter_calendar_week: ^3.0.0
  calendar_timeline: ^1.1.2
  file_picker: ^5.2.6
  location: ^4.4.0
  image_picker: ^0.8.7
  maps_launcher: ^2.2.0
  custom_sliding_segmented_control: ^1.7.4
  flutter_advanced_segment: ^3.0.1
  tap_to_expand: ^0.6.1
  flutter_svg: ^2.0.5
  firebase_messaging: ^14.6.3
  flutter_local_notifications: ^13.0.0
  firebase_core: ^2.2.0
  dots_indicator: ^2.1.0
  overlay_support: ^2.1.0
  razorpay_flutter: 1.3.3
  url_launcher: ^6.1.10
  qr_code_scanner: ^1.0.1
  time_planner: ^0.1.1
  lottie: ^2.3.2
  camera: ^0.10.4
  fl_chart: ^0.62.0
  barcode_scan2: ^4.2.4
  stop_watch_timer: ^2.0.0
  nice_intro: ^0.2.1
  json_annotation: ^4.8.1
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.3.3





flutter:
  
  
  
  uses-material-design: true

  
  assets:
    - assets/
    - assets/images/
    - assets/lottie/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
